In [2]:
import pandas as pd

In [3]:
import os

data_path = "../data/raw"

print(os.listdir(data_path))

['olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv', 'olist_sellers_dataset.csv', 'product_category_name_translation.csv']

In [4]:
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
print("Rows:", orders.shape[0])
print("Columns:", orders.shape[1])

print("\nColumn Names:")
print(orders.columns.tolist())

Rows: 99441
Columns: 8

Column Names:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

In [6]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [7]:
orders[orders["order_delivered_customer_date"].isnull()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [8]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [9]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [10]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [11]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [12]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [13]:
orders["customer_id"].nunique()

99441

In [14]:
print("First Order Date:", orders["order_purchase_timestamp"].min())
print("Last Order Date:", orders["order_purchase_timestamp"].max())

First Order Date: 2016-09-04 21:15:19
Last Order Date: 2018-10-17 17:30:18

In [15]:
orders["order_id"].isnull().sum()

np.int64(0)

In [16]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [17]:
orders[orders["order_approved_at"].isnull()]["order_status"].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [18]:
orders[orders["order_delivered_customer_date"].isnull()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [19]:
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [20]:
print("Rows:", order_items.shape[0])
print("Columns:", order_items.shape[1])

print("\nColumn Names:")
print(order_items.columns.tolist())

Rows: 112650
Columns: 7

Column Names:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

In [21]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [22]:
order_items.duplicated(subset=["order_id", "order_item_id"]).sum()

np.int64(0)

In [23]:
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [24]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"]
)

In [25]:
order_items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [26]:
print("Minimum Price:", order_items["price"].min())
print("Minimum Freight Value:", order_items["freight_value"].min())

print("Zero Price:", (order_items["price"] == 0).sum())
print("Zero Freight Value:", (order_items["freight_value"] == 0).sum())

Minimum Price: 0.85
Minimum Freight Value: 0.0
Zero Price: 0
Zero Freight Value: 383

In [27]:
zero_freight_pct = (
    (order_items["freight_value"] == 0).sum()
    / len(order_items)
) * 100

print("Zero Freight Percentage:", zero_freight_pct)

Zero Freight Percentage: 0.33999112294718153

In [28]:
customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [29]:
print("Rows:", customers.shape[0])
print("Columns:", customers.shape[1])

print("\nColumn Names:")
print(customers.columns.tolist())

Rows: 99441
Columns: 5

Column Names:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

In [30]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [31]:
print("Duplicate customer_id:", customers["customer_id"].duplicated().sum())

print("Unique customer IDs:", customers["customer_id"].nunique())
print("Unique customers:", customers["customer_unique_id"].nunique())

Duplicate customer_id: 0
Unique customer IDs: 99441
Unique customers: 96096

In [32]:
customer_order_counts = customers["customer_unique_id"].value_counts()

print("Customers with multiple records:",
      (customer_order_counts > 1).sum())

print("\nMaximum records for one customer:",
      customer_order_counts.max())

Customers with multiple records: 2997

Maximum records for one customer: 17

In [33]:
print("Unique Cities:", customers["customer_city"].nunique())
print("Unique States:", customers["customer_state"].nunique())

print("\nTop 10 States:")
print(customers["customer_state"].value_counts().head(10))

Unique Cities: 4119
Unique States: 27

Top 10 States:
customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
Name: count, dtype: int64

In [34]:
print(sorted(customers["customer_state"].unique()))

['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO']

In [35]:
print("Minimum ZIP Prefix:", customers["customer_zip_code_prefix"].min())
print("Maximum ZIP Prefix:", customers["customer_zip_code_prefix"].max())

print("Unique ZIP Prefixes:",
      customers["customer_zip_code_prefix"].nunique())

Minimum ZIP Prefix: 1003
Maximum ZIP Prefix: 99990
Unique ZIP Prefixes: 14994

In [36]:
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [37]:
print("Rows:", products.shape[0])
print("Columns:", products.shape[1])

print("\nColumn Names:")
print(products.columns.tolist())

Rows: 32951
Columns: 9

Column Names:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

In [38]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [39]:
products[products["product_category_name"].isnull()].head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,16.0,2.0,11.0
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN,300.0,16.0,7.0,11.0
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN,300.0,18.0,8.0,14.0
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN,200.0,22.0,14.0,14.0
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN,1400.0,25.0,25.0,25.0

In [40]:
used_products = order_items["product_id"].isin(
    products.loc[products["product_category_name"].isnull(), "product_id"]
)

print("Missing-category products used in orders:", used_products.sum())

Missing-category products used in orders: 1603

In [41]:
missing_category_products = products[
    products["product_category_name"].isnull()
]["product_id"]

missing_category_sales = order_items[
    order_items["product_id"].isin(missing_category_products)
]

print("Order Items:", len(missing_category_sales))
print("Total Sales:", missing_category_sales["price"].sum())
print("Average Price:", missing_category_sales["price"].mean())

Order Items: 1603
Total Sales: 179535.28
Average Price: 111.99955084217093

In [42]:
print("Duplicate Product IDs:", products["product_id"].duplicated().sum())
print("Unique Product IDs:", products["product_id"].nunique())

Duplicate Product IDs: 0
Unique Product IDs: 32951

In [43]:
print("Zero Weight:", (products["product_weight_g"] == 0).sum())
print("Negative Weight:", (products["product_weight_g"] < 0).sum())

print("Zero Length:", (products["product_length_cm"] == 0).sum())
print("Zero Height:", (products["product_height_cm"] == 0).sum())
print("Zero Width:", (products["product_width_cm"] == 0).sum())

Zero Weight: 4
Negative Weight: 0
Zero Length: 0
Zero Height: 0
Zero Width: 0

In [44]:
zero_weight_products = products[
    products["product_weight_g"] == 0
]

print("Zero-weight products:", len(zero_weight_products))

print("\nUsed in orders:",
      zero_weight_products["product_id"].isin(
          order_items["product_id"]
      ).sum())

Zero-weight products: 4

Used in orders: 4

In [45]:
payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [46]:
print("Rows:", payments.shape[0])
print("Columns:", payments.shape[1])

print("\nColumn Names:")
print(payments.columns.tolist())

Rows: 103886
Columns: 5

Column Names:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

In [47]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [48]:
print("Minimum Payment Value:", payments["payment_value"].min())
print("Zero Payment Value:", (payments["payment_value"] == 0).sum())
print("Negative Payment Value:", (payments["payment_value"] < 0).sum())

print("\nMinimum Installments:", payments["payment_installments"].min())
print("Zero Installments:", (payments["payment_installments"] == 0).sum())
print("Negative Installments:", (payments["payment_installments"] < 0).sum())

Minimum Payment Value: 0.0
Zero Payment Value: 9
Negative Payment Value: 0

Minimum Installments: 0
Zero Installments: 2
Negative Installments: 0

In [49]:
print("Zero Payment Records:")
print(payments[payments["payment_value"] == 0])

print("\nZero Installment Records:")
print(payments[payments["payment_installments"] == 0])

Zero Payment Records:
                                order_id  payment_sequential payment_type  \
19922   8bcbe01d44d147f901cd3192671144db                   4      voucher
36822   fa65dad1b0e818e3ccc5cb0e39231352                  14      voucher
43744   6ccb433e00daae1283ccc956189c82ae                   4      voucher
51280   4637ca194b6387e2d538dc89b124b0ee                   1  not_defined
57411   00b1cb0320190ca0daa2c88b35206009                   1  not_defined
62674   45ed6e85398a87c253db47c2d9f48216                   3      voucher
77885   fa65dad1b0e818e3ccc5cb0e39231352                  13      voucher
94427   c8c528189310eaa44a745b8d9d26908b                   1  not_defined
100766  b23878b3e8eb4d25a158f57d96331b18                   4      voucher

        payment_installments  payment_value
19922                      1            0.0
36822                      1            0.0
43744                      1            0.0
51280                      1            0.0
57411                      1            0.0
62674                      1            0.0
77885                      1            0.0
94427                      1            0.0
100766                     1            0.0

Zero Installment Records:
                               order_id  payment_sequential payment_type  \
46982  744bade1fcf9ff3f31d860ace076d422                   2  credit_card
79014  1a57108394169c0b47d8f876acc9ba2d                   2  credit_card

       payment_installments  payment_value
46982                     0          58.69
79014                     0         129.94

In [50]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [51]:
payment_revenue = payments.groupby("payment_type")["payment_value"].sum().sort_values(ascending=False)

print(payment_revenue)

payment_type
credit_card    12542084.19
boleto          2869361.27
voucher          379436.87
debit_card       217989.79
not_defined           0.00
Name: payment_value, dtype: float64

In [52]:
print("Maximum Installments:",
      payments["payment_installments"].max())

print("\nInstallment Distribution:")
print(payments["payment_installments"].value_counts().sort_index())

Maximum Installments: 24

Installment Distribution:
payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [53]:
pd.crosstab(
    payments["payment_type"],
    payments["payment_installments"]
)

payment_installments,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,20,21,22,23,24
payment_type,,,,,,,,,,,,,,,,,,,,,
boleto,0,19784,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
credit_card,2,25455,12413,10461,7098,5239,3920,1626,4268,644,...,15,74,5,8,27,17,3,1,1,18
debit_card,0,1529,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
not_defined,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
voucher,0,5775,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [55]:
print("Rows:", reviews.shape[0])
print("Columns:", reviews.shape[1])

print("\nColumn Names:")
print(reviews.columns.tolist())

Rows: 99224
Columns: 7

Column Names:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

In [56]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [57]:
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [58]:
print("Duplicate review_id:", reviews["review_id"].duplicated().sum())
print("Duplicate order_id:", reviews["order_id"].duplicated().sum())

Duplicate review_id: 814
Duplicate order_id: 551

In [59]:
reviews["order_id"].value_counts().head(10)

order_id
c88b1d1b157a9999ce368f218a407141    3
df56136b8031ecd28e200bb18e6ddb2e    3
03c939fd7fd3b38f8485a0f95798f1f6    3
8e17072ec97ce29f0e1f111e598b0c85    3
cf73e2cb1f4a9480ed70c154da3d954a    2
169d7e0fd71d624d306f132acd791cbe    2
1c308eca3f339414a92e518e2a2e5ee9    2
2002ea16e75277eaa0b5d78632048540    2
1d297b4800ed1a3c5b0944d84c01ee99    2
0176a6846bcb3b0d3aa3116a9a768597    2
Name: count, dtype: int64

In [60]:
reviews[reviews["review_id"].duplicated(keep=False)].sort_values("review_id").head(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5,NaN,NaN,2018-03-02 00:00:00,2018-03-05 01:43:30
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,NaN,NaN,2018-03-02 00:00:00,2018-03-05 01:43:30
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09 00:00:00,2017-09-13 09:52:44
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09 00:00:00,2017-09-13 09:52:44

In [61]:
print("Total review rows:", len(reviews))
print("Unique review IDs:", reviews["review_id"].nunique())

Total review rows: 99224
Unique review IDs: 98410

In [62]:
print("Minimum review score:", reviews["review_score"].min())
print("Maximum review score:", reviews["review_score"].max())
print("Unique review scores:", sorted(reviews["review_score"].unique()))

Minimum review score: 1
Maximum review score: 5
Unique review scores: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [63]:
print("Average Review Score:", reviews["review_score"].mean())

Average Review Score: 4.08642062404257

In [64]:
review_date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in review_date_columns:
    reviews[col] = pd.to_datetime(reviews[col])

reviews[review_date_columns].dtypes

review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [65]:
print("First Review Date:", reviews["review_creation_date"].min())
print("Last Review Date:", reviews["review_creation_date"].max())

First Review Date: 2016-10-02 00:00:00
Last Review Date: 2018-08-31 00:00:00

In [66]:
print("Reviews with missing order_id:", reviews["order_id"].isnull().sum())

Reviews with missing order_id: 0

In [67]:
review_id_counts = reviews["review_id"].value_counts()

print("Review IDs appearing more than once:", (review_id_counts > 1).sum())
print("Maximum rows for one review ID:", review_id_counts.max())

Review IDs appearing more than once: 789
Maximum rows for one review ID: 3

In [68]:
order_review_counts = reviews["order_id"].value_counts()

print("Orders with more than one review:", (order_review_counts > 1).sum())
print("Maximum reviews for one order:", order_review_counts.max())

Orders with more than one review: 547
Maximum reviews for one order: 3

In [69]:
multiple_review_scores = (
    reviews.groupby("order_id")["review_score"]
    .nunique()
)

print("Orders with multiple different review scores:",
      (multiple_review_scores > 1).sum())

Orders with multiple different review scores: 202

In [70]:
duplicate_reviews = reviews[
    reviews["review_id"].duplicated(keep=False)
].sort_values("review_id")

duplicate_reviews.head(20)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07,2018-03-08 03:00:53
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5,NaN,NaN,2018-03-02,2018-03-05 01:43:30
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,NaN,NaN,2018-03-02,2018-03-05 01:43:30
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09,2017-09-13 09:52:44
89712,0288d42bef3dfe36930740c9588a570f,33d8795f04dd631f3480d7aaf90da3dc,3,NaN,NaN,2017-07-29,2017-07-31 17:11:04
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3,NaN,NaN,2017-07-29,2017-07-31 17:11:04
47495,02aa7f5f75e964e3c7efa59a1f515281,d8e17d5f7dacf0970d316e7c03e741e8,3,NaN,NaN,2017-07-27,2017-07-29 15:09:50
95860,02aa7f5f75e964e3c7efa59a1f515281,db92613c074f00e53066388d48ad7512,3,NaN,NaN,2017-07-27,2017-07-29 15:09:50
71165,034528cb00b6bc981847acafbdf2ae0b,e1e8e3bca903de27e9a1c72b5a5795e0,1,NaN,NaN,2017-05-14,2017-05-15 02:17:38
81094,034528cb00b6bc981847acafbdf2ae0b,3d3742a96f24a8fe4e2e57628807e476,1,NaN,NaN,2017-05-14,2017-05-15 02:17:38
1988,03a6a25db577d0689440933055111897,2acfdc5131ff2cf4433e668454c9784c,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15,2017-12-16 01:32:18
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15,2017-12-16 01:32:18
21587,0467560f511c516ddaa54a60edb0c291,0c995611a99f81268d859184a416f1db,5,NaN,NaN,2017-02-09,2017-02-14 15:58:44
24901,0467560f511c516ddaa54a60edb0c291,55b2e390d5d80ada31ad1b795ebeb087,5,NaN,NaN,2017-02-09,2017-02-14 15:58:44

In [71]:
exact_duplicate_rows = reviews.duplicated().sum()

print("Completely duplicate rows:", exact_duplicate_rows)

Completely duplicate rows: 0

In [72]:
missing_orders_in_reviews = ~reviews["order_id"].isin(orders["order_id"])

print(
    "Reviews with order_id not found in orders:",
    missing_orders_in_reviews.sum()
)

Reviews with order_id not found in orders: 0

In [73]:
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

print("Rows:", sellers.shape[0])
print("Columns:", sellers.shape[1])
print("\nColumns:")
print(sellers.columns.tolist())

Rows: 3095
Columns: 4

Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [74]:
print(sellers.isnull().sum())

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [75]:
print("Duplicate seller IDs:", sellers["seller_id"].duplicated().sum())

Duplicate seller IDs: 0

In [76]:
print("Unique seller cities:", sellers["seller_city"].nunique())
print("Unique seller states:", sellers["seller_state"].nunique())

print("\nTop seller states:")
print(sellers["seller_state"].value_counts().head(10))

Unique seller cities: 611
Unique seller states: 23

Top seller states:
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
Name: count, dtype: int64

In [77]:
print("Unique seller ZIP prefixes:", sellers["seller_zip_code_prefix"].nunique())
print("Minimum ZIP prefix:", sellers["seller_zip_code_prefix"].min())
print("Maximum ZIP prefix:", sellers["seller_zip_code_prefix"].max())

Unique seller ZIP prefixes: 2246
Minimum ZIP prefix: 1001
Maximum ZIP prefix: 99730

In [78]:
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

print("Rows:", geolocation.shape[0])
print("Columns:", geolocation.shape[1])
print("\nColumns:")
print(geolocation.columns.tolist())

Rows: 1000163
Columns: 5

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

In [79]:
print(geolocation.isnull().sum())

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [80]:
print("Duplicate rows:", geolocation.duplicated().sum())

Duplicate rows: 261831

In [81]:
print("Unique ZIP prefixes:", geolocation["geolocation_zip_code_prefix"].nunique())

Unique ZIP prefixes: 19015

In [82]:
category_translation = pd.read_csv(
    "../data/raw/product_category_name_translation.csv"
)

print("Rows:", category_translation.shape[0])
print("Columns:", category_translation.shape[1])
print("\nColumns:")
print(category_translation.columns.tolist())

Rows: 71
Columns: 2

Columns:
['product_category_name', 'product_category_name_english']

In [83]:
print(category_translation.isnull().sum())

product_category_name            0
product_category_name_english    0
dtype: int64

In [84]:
orders_clean = orders.copy()

print("Original rows:", len(orders))
print("Clean copy rows:", len(orders_clean))

Original rows: 99441
Clean copy rows: 99441

In [85]:
print(orders_clean.isnull().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [86]:
print(
    orders_clean[orders_clean["order_delivered_customer_date"].isnull()]
    ["order_status"]
    .value_counts()
)

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [87]:
orders_clean[
    (orders_clean["order_status"] == "delivered") &
    (orders_clean["order_delivered_customer_date"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [88]:
print(
    orders_clean[orders_clean["order_approved_at"].isnull()]
    ["order_status"]
    .value_counts()
)

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [89]:
print("Duplicate order IDs:", orders_clean["order_id"].duplicated().sum())

Duplicate order IDs: 0

In [90]:
print(
    "Delivered before purchase:",
    (orders_clean["order_delivered_customer_date"] < orders_clean["order_purchase_timestamp"]).sum()
)

print(
    "Estimated delivery before purchase:",
    (orders_clean["order_estimated_delivery_date"] < orders_clean["order_purchase_timestamp"]).sum()
)

Delivered before purchase: 0
Estimated delivery before purchase: 0

In [91]:
orders_clean["order_year"] = orders_clean["order_purchase_timestamp"].dt.year
orders_clean["order_month"] = orders_clean["order_purchase_timestamp"].dt.month
orders_clean["order_month_name"] = orders_clean["order_purchase_timestamp"].dt.month_name()

print(orders_clean[
    ["order_purchase_timestamp", "order_year", "order_month", "order_month_name"]
].head())

  order_purchase_timestamp  order_year  order_month order_month_name
0      2017-10-02 10:56:33        2017           10          October
1      2018-07-24 20:41:37        2018            7             July
2      2018-08-08 08:38:49        2018            8           August
3      2017-11-18 19:28:06        2017           11         November
4      2018-02-13 21:18:39        2018            2         February

In [92]:
print("Rows:", orders_clean.shape[0])
print("Columns:", orders_clean.shape[1])

print("\nData types:")
print(orders_clean.dtypes)

Rows: 99441
Columns: 11

Data types:
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
order_year                                int32
order_month                               int32
order_month_name                            str
dtype: object

In [93]:
orders_clean.to_csv("../data/cleaned/orders_clean.csv", index=False)
print("Cleaned Orders dataset saved successfully!")

Cleaned Orders dataset saved successfully!

In [94]:
order_items_clean = order_items.copy()

print("Original rows:", len(order_items))
print("Clean copy rows:", len(order_items_clean))

Original rows: 112650
Clean copy rows: 112650

In [95]:
print(order_items_clean.isnull().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [96]:
print(
    "Duplicate order-item records:",
    order_items_clean.duplicated(
        subset=["order_id", "order_item_id"]
    ).sum()
)

Duplicate order-item records: 0

In [97]:
print("Negative prices:", (order_items_clean["price"] < 0).sum())
print("Negative freight values:", (order_items_clean["freight_value"] < 0).sum())

Negative prices: 0
Negative freight values: 0

In [98]:
print("Zero prices:", (order_items_clean["price"] == 0).sum())
print("Zero freight values:", (order_items_clean["freight_value"] == 0).sum())

Zero prices: 0
Zero freight values: 383

In [99]:
print(order_items_clean.dtypes)

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [100]:
order_items_clean.to_csv(
    "../data/cleaned/order_items_clean.csv",
    index=False
)

print("Cleaned Order Items dataset saved successfully!")

Cleaned Order Items dataset saved successfully!

In [101]:
customers_clean = customers.copy()

print("Original rows:", len(customers))
print("Clean copy rows:", len(customers_clean))

Original rows: 99441
Clean copy rows: 99441

In [102]:
print(
    "Duplicate customer_id:",
    customers_clean["customer_id"].duplicated().sum()
)

print(
    "Duplicate customer_unique_id:",
    customers_clean["customer_unique_id"].duplicated().sum()
)

Duplicate customer_id: 0
Duplicate customer_unique_id: 3345

In [103]:
print(customers_clean.isnull().sum())

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [104]:
print(customers_clean.dtypes)

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [105]:
print(
    "Negative ZIP prefixes:",
    (customers_clean["customer_zip_code_prefix"] < 0).sum()
)

print(
    "Zero ZIP prefixes:",
    (customers_clean["customer_zip_code_prefix"] == 0).sum()
)

Negative ZIP prefixes: 0
Zero ZIP prefixes: 0

In [106]:
customers_clean.to_csv(
    "../data/cleaned/customers_clean.csv",
    index=False
)

print("Cleaned Customers dataset saved successfully!")

Cleaned Customers dataset saved successfully!

In [107]:
products_clean = products.copy()

print("Original rows:", len(products))
print("Clean copy rows:", len(products_clean))

Original rows: 32951
Clean copy rows: 32951

In [108]:
print(products_clean.isnull().sum())

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [109]:
print(
    "Duplicate product_id:",
    products_clean["product_id"].duplicated().sum()
)

Duplicate product_id: 0

In [110]:
numeric_columns = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

print(products_clean[numeric_columns].lt(0).sum())

product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [111]:
print(
    products_clean[numeric_columns].eq(0).sum()
)

product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              4
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [112]:
products_clean.loc[
    products_clean["product_weight_g"] == 0,
    "product_weight_g"
] = pd.NA

print(
    "Zero weights remaining:",
    (products_clean["product_weight_g"] == 0).sum()
)

Zero weights remaining: 0

In [113]:
print(products_clean.dtypes)

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [114]:
products_clean["product_category_name"] = products_clean[
    "product_category_name"
].fillna("Unknown")

print(
    "Missing categories remaining:",
    products_clean["product_category_name"].isnull().sum()
)

Missing categories remaining: 0

In [115]:
print(products_clean.isnull().sum())

product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                6
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [116]:
products_clean.to_csv(
    "../data/cleaned/products_clean.csv",
    index=False
)

print("Cleaned Products dataset saved successfully!")

Cleaned Products dataset saved successfully!

In [117]:
payments_clean = payments.copy()

print("Original rows:", len(payments))
print("Clean copy rows:", len(payments_clean))

Original rows: 103886
Clean copy rows: 103886

In [118]:
print(payments_clean.isnull().sum())

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [119]:
print("Duplicate rows:", payments_clean.duplicated().sum())

Duplicate rows: 0

In [120]:
print("Negative payment values:",
      (payments_clean["payment_value"] < 0).sum())

print("Zero payment values:",
      (payments_clean["payment_value"] == 0).sum())

Negative payment values: 0
Zero payment values: 9

In [121]:
payments_clean[
    payments_clean["payment_value"] == 0
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [122]:
print("Negative installments:",
      (payments_clean["payment_installments"] < 0).sum())

print("Zero installments:",
      (payments_clean["payment_installments"] == 0).sum())

Negative installments: 0
Zero installments: 2

In [123]:
payments_clean[
    payments_clean["payment_installments"] == 0
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [124]:
print(payments_clean.dtypes)

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [125]:
print("Final shape:", payments_clean.shape)

print("\nMissing values:")
print(payments_clean.isnull().sum())

Final shape: (103886, 5)

Missing values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [126]:
payments_clean.to_csv(
    "../data/cleaned/payments_clean.csv",
    index=False
)

print("Cleaned Payments dataset saved successfully!")

Cleaned Payments dataset saved successfully!

In [127]:
reviews_clean = reviews.copy()

print("Original rows:", len(reviews))
print("Clean copy rows:", len(reviews_clean))

Original rows: 99224
Clean copy rows: 99224

In [128]:
print(reviews_clean.isnull().sum())

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [129]:
print("Duplicate rows:", reviews_clean.duplicated().sum())

Duplicate rows: 0

In [130]:
print("Minimum score:", reviews_clean["review_score"].min())
print("Maximum score:", reviews_clean["review_score"].max())
print("Unique scores:", sorted(reviews_clean["review_score"].unique()))

Minimum score: 1
Maximum score: 5
Unique scores: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [131]:
print("Duplicate review_id:", reviews_clean["review_id"].duplicated().sum())
print("Unique review_id:", reviews_clean["review_id"].nunique())
print("Total rows:", len(reviews_clean))

Duplicate review_id: 814
Unique review_id: 98410
Total rows: 99224

In [132]:
print(
    "Reviews before creation date:",
    (reviews_clean["review_answer_timestamp"] < reviews_clean["review_creation_date"]).sum()
)

Reviews before creation date: 0

In [133]:
reviews_clean["review_comment_title"] = reviews_clean[
    "review_comment_title"
].fillna("No Title")

reviews_clean["review_comment_message"] = reviews_clean[
    "review_comment_message"
].fillna("No Comment")

print(reviews_clean[
    ["review_comment_title", "review_comment_message"]
].isnull().sum())

review_comment_title      0
review_comment_message    0
dtype: int64

In [134]:
print("Final Reviews shape:", reviews_clean.shape)
print("\nMissing values:")
print(reviews_clean.isnull().sum())
print("\nData types:")
print(reviews_clean.dtypes)

Final Reviews shape: (99224, 7)

Missing values:
review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

Data types:
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [135]:
reviews_clean.to_csv(
    "../data/cleaned/reviews_clean.csv",
    index=False
)

print("Cleaned Reviews dataset saved successfully!")

Cleaned Reviews dataset saved successfully!

In [136]:
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

sellers_clean = sellers.copy()

print("Original rows:", len(sellers))
print("Clean copy rows:", len(sellers_clean))

Original rows: 3095
Clean copy rows: 3095

In [137]:
sellers_clean = sellers.copy()

print("Original rows:", len(sellers))
print("Clean copy rows:", len(sellers_clean))

Original rows: 3095
Clean copy rows: 3095

In [138]:
print(sellers_clean.isnull().sum())

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [139]:
sellers_clean.to_csv(
    "../data/cleaned/sellers_clean.csv",
    index=False
)

print("Cleaned Sellers dataset saved successfully!")

Cleaned Sellers dataset saved successfully!

In [140]:
geolocation_clean = geolocation.copy()

print("Original rows:", len(geolocation))
print("Clean copy rows:", len(geolocation_clean))

Original rows: 1000163
Clean copy rows: 1000163

In [141]:
before = len(geolocation_clean)

geolocation_clean = geolocation_clean.drop_duplicates()

after = len(geolocation_clean)

print("Rows before:", before)
print("Rows after:", after)
print("Rows removed:", before - after)

Rows before: 1000163
Rows after: 738332
Rows removed: 261831

In [142]:
print(geolocation_clean.isnull().sum())

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [143]:
print("Invalid latitude:", ((geolocation_clean["geolocation_lat"] < -90) | 
                            (geolocation_clean["geolocation_lat"] > 90)).sum())

print("Invalid longitude:", ((geolocation_clean["geolocation_lng"] < -180) | 
                             (geolocation_clean["geolocation_lng"] > 180)).sum())

Invalid latitude: 0
Invalid longitude: 0

In [144]:
geolocation_clean.to_csv(
    "../data/cleaned/geolocation_clean.csv",
    index=False
)

print("Cleaned Geolocation dataset saved successfully!")

Cleaned Geolocation dataset saved successfully!

In [145]:
category_translation = pd.read_csv(
    "../data/raw/product_category_name_translation.csv"
)

print(category_translation.shape)
print(category_translation.columns.tolist())

(71, 2)
['product_category_name', 'product_category_name_english']

In [146]:
print(category_translation.isnull().sum())

product_category_name            0
product_category_name_english    0
dtype: int64

In [147]:
category_translation_clean = category_translation.copy()

print("Original rows:", len(category_translation))
print("Clean copy rows:", len(category_translation_clean))

Original rows: 71
Clean copy rows: 71

In [148]:
category_translation_clean.to_csv(
    "../data/cleaned/category_translation_clean.csv",
    index=False
)

print("Cleaned Category Translation dataset saved successfully!")

Cleaned Category Translation dataset saved successfully!

In [149]:
sales_data = (
    order_items_clean
    .merge(orders_clean, on="order_id", how="left")
    .merge(customers_clean, on="customer_id", how="left")
    .merge(products_clean, on="product_id", how="left")
    .merge(category_translation_clean, on="product_category_name", how="left")
    .merge(sellers_clean, on="seller_id", how="left")
)

print("Sales dataset shape:", sales_data.shape)

Sales dataset shape: (112650, 33)

In [150]:
sales_data["item_revenue"] = sales_data["price"]

sales_data["total_item_value"] = (
    sales_data["price"] + sales_data["freight_value"]
)

print(
    sales_data[
        ["price", "freight_value", "item_revenue", "total_item_value"]
    ].head()
)

    price  freight_value  item_revenue  total_item_value
0   58.90          13.29         58.90             72.19
1  239.90          19.93        239.90            259.83
2  199.00          17.87        199.00            216.87
3   12.99          12.79         12.99             25.78
4  199.90          18.14        199.90            218.04

In [151]:
print("Missing values after merging:")
print(sales_data.isnull().sum().sort_values(ascending=False).head(10))

Missing values after merging:
order_delivered_customer_date    2454
product_category_name_english    1627
product_name_lenght              1603
product_description_lenght       1603
product_photos_qty               1603
order_delivered_carrier_date     1194
product_weight_g                   26
product_width_cm                   18
product_height_cm                  18
product_length_cm                  18
dtype: int64

In [152]:
sales_data["product_category_name_english"] = (
    sales_data["product_category_name_english"]
    .fillna("Unknown")
)

print(
    sales_data["product_category_name_english"]
    .isnull()
    .sum()
)

0

In [153]:
print("Final sales dataset shape:", sales_data.shape)
print("Unique orders:", sales_data["order_id"].nunique())
print("Unique products:", sales_data["product_id"].nunique())
print("Unique customers:", sales_data["customer_id"].nunique())

Final sales dataset shape: (112650, 35)
Unique orders: 98666
Unique products: 32951
Unique customers: 98666

In [154]:
total_revenue = sales_data["item_revenue"].sum()
total_orders = sales_data["order_id"].nunique()
total_customers = sales_data["customer_id"].nunique()
total_products = sales_data["product_id"].nunique()

average_order_value = total_revenue / total_orders

print("Total Revenue:", round(total_revenue, 2))
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)
print("Total Products Sold:", total_products)
print("Average Order Value:", round(average_order_value, 2))

Total Revenue: 13591643.7
Total Orders: 98666
Total Customers: 98666
Total Products Sold: 32951
Average Order Value: 137.75

In [155]:
total_unique_customers = sales_data["customer_unique_id"].nunique()

print("Actual Unique Customers:", total_unique_customers)

Actual Unique Customers: 95420

In [156]:
monthly_sales = (
    sales_data
    .groupby(["order_year", "order_month"], as_index=False)["item_revenue"]
    .sum()
    .sort_values(["order_year", "order_month"])
)

monthly_sales["year_month"] = (
    monthly_sales["order_year"].astype(str)
    + "-"
    + monthly_sales["order_month"].astype(str).str.zfill(2)
)

print(monthly_sales)

    order_year  order_month  item_revenue year_month
0         2016            9        267.36    2016-09
1         2016           10      49507.66    2016-10
2         2016           12         10.90    2016-12
3         2017            1     120312.87    2017-01
4         2017            2     247303.02    2017-02
5         2017            3     374344.30    2017-03
6         2017            4     359927.23    2017-04
7         2017            5     506071.14    2017-05
8         2017            6     433038.60    2017-06
9         2017            7     498031.48    2017-07
10        2017            8     573971.68    2017-08
11        2017            9     624401.69    2017-09
12        2017           10     664219.43    2017-10
13        2017           11    1010271.37    2017-11
14        2017           12     743914.17    2017-12
15        2018            1     950030.36    2018-01
16        2018            2     844178.71    2018-02
17        2018            3     983213.44    2018-03
18        2018            4     996647.75    2018-04
19        2018            5     996517.68    2018-05
20        2018            6     865124.31    2018-06
21        2018            7     895507.22    2018-07
22        2018            8     854686.33    2018-08
23        2018            9        145.00    2018-09

In [157]:
sales_data.to_csv(
    "../data/cleaned/sales_data.csv",
    index=False
)

print("Final integrated sales dataset saved successfully!")

Final integrated sales dataset saved successfully!

In [158]:
datetime_columns = [
    "shipping_limit_date",
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in datetime_columns:
    sales_data[col] = pd.to_datetime(
        sales_data[col],
        errors="coerce"
    )

In [159]:
mysql_file = "../data/cleaned/sales_data_mysql.csv"

sales_data.to_csv(
    mysql_file,
    index=False,
    na_rep="\\N"
)

print("MySQL-ready CSV created successfully!")

MySQL-ready CSV created successfully!

In [161]:
payments_clean.to_csv(
    "../data/cleaned/payments_clean.csv",
    index=False
)